/**
 * dsh-rrp — the activity ledger: WHO changed the world, and WHAT changed.
 *
 * The Chronicler/Summarizer run in the background (D3: body text first, state
 * inference after), so without an explicit ledger the player cannot tell which
 * agent produced a state change. Every writer appends one bounded entry here;
 * the right-sidebar panel renders the tail as an attribution line.
 *
 * The ledger is HOST-SIDE, IN-MEMORY, and exposed over `GET /dsh-rrp/activity`.
 * It is deliberately not a session event: the host refuses to load a log
 * containing a plugin-invented event type, and the ledger is player-facing
 * bookkeeping that must never reach the model anyway. Losing it on restart is
 * acceptable — it only describes recent passes.
 *
 * Dependency-free: shared by host writers and the client bundle.
 */

/** Which writer produced an entry. */
export type RrpActor = 'chronicler' | 'summarizer' | 'player' | 'card' | 'scribe'

/** Which artifact the writer touched. */
export type RrpTarget = 'world-state' | 'summary' | 'sediment'

/** Lifecycle of one writer pass. */
export type RrpPhase = 'started' | 'committed' | 'failed' | 'corrected'

/** One attribution entry. */
export interface RrpActivity {
  /** Groups a `started` entry with its terminal entry. */
  id: string
  /** ISO timestamp, generated by the writer. */
  at: string
  actor: RrpActor
  target: RrpTarget
  phase: RrpPhase
  /** Human change digest (committed/corrected), error text (failed), or none. */
  detail?: string
}

/** The panel only needs a recent tail; the ledger stays bounded. */
export const ACTIVITY_LIMIT = 20

/** The ledger state. */
export interface RrpActivityLog {
  entries: RrpActivity[]
}

/** A fresh empty ledger (never share one object across sessions). */
export function emptyActivityLog(): RrpActivityLog {
  return { entries: [] }
}

/** Append one entry and keep the newest `ACTIVITY_LIMIT`. Pure. */
export function appendActivity(log: RrpActivityLog, entry: RrpActivity): RrpActivityLog {
  return { entries: [...log.entries, entry].slice(-ACTIVITY_LIMIT) }
}

/** The most recent entry for a target, if any. */
export function lastActivity(log: RrpActivityLog, target: RrpTarget): RrpActivity | undefined {
  for (let index = log.entries.length - 1; index >= 0; index -= 1) {
    const entry = log.entries[index]
    if (entry?.target === target) return entry
  }
  return undefined
}

/** Whether a writer is still running for a target (tail is a `started` entry). */
export function pendingActivity(log: RrpActivityLog, target: RrpTarget): RrpActivity | undefined {
  const last = lastActivity(log, target)
  return last?.phase === 'started' ? last : undefined
}

/** Per-session ledgers. Bounded by `ACTIVITY_LIMIT` each. */
const LEDGERS = new Map<string, RrpActivityLog>()

/** Record one entry. Never throws; the ledger must not break the writer. */
export function recordActivity(sessionId: string, entry: RrpActivity): void {
  try {
    LEDGERS.set(sessionId, appendActivity(LEDGERS.get(sessionId) ?? emptyActivityLog(), entry))
  } catch {
    /* the ledger is best-effort; the authoritative write already happened */
  }
}

/** Read one session's ledger tail. */
export function readActivity(sessionId: string): RrpActivityLog {
  return LEDGERS.get(sessionId) ?? emptyActivityLog()
}

/** Forget one session's ledger (called when a session is disposed). */
export function forgetActivity(sessionId: string): void {
  LEDGERS.delete(sessionId)
}
