/**
 * dsh-rrp — the activity ledger: WHO changed the world, and WHAT changed.
 *
 * The Chronicler/Summarizer run in the background (D3: body text first, state
 * inference after), so without an explicit ledger the player cannot tell which
 * agent produced a state change. Every writer appends one bounded entry to the
 * session log; the right-sidebar panel renders the tail as an attribution line.
 *
 * Dependency-free: shared by host writers, the projection fold, and the client
 * bundle. Writers generate `id`/`at` (node-only crypto/time stays host-side).
 */

/** Which writer produced an entry. */
export type RrpActor = 'chronicler' | 'summarizer' | 'player' | 'card'

/** Which artifact the writer touched. */
export type RrpTarget = 'world-state' | 'summary'

/** Lifecycle of one writer pass. */
export type RrpPhase = 'started' | 'committed' | 'failed' | 'corrected'

/** One attribution entry. */
export interface RrpActivity {
  /** Groups a `started` entry with its terminal entry. */
  id: string
  /** ISO timestamp, generated by the writer. */
  at: string
  actor: RrpActor
  target: RrpTarget
  phase: RrpPhase
  /** Human change digest (committed/corrected), error text (failed), or none. */
  detail?: string
}

/** Session event type carrying one activity entry (append-only). */
export const ACTIVITY_EVENT = 'rrp/activity'

/** Projection key, also the client `useProjection(key)` lookup key. */
export const ACTIVITY_KEY = 'rrpActivity'

/** The panel only needs a recent tail; the ledger stays bounded. */
export const ACTIVITY_LIMIT = 20

/** The ledger projection state. */
export interface RrpActivityLog {
  entries: RrpActivity[]
}

/** A fresh empty ledger (never share one object across sessions). */
export function emptyActivityLog(): RrpActivityLog {
  return { entries: [] }
}

/** Append one entry and keep the newest `ACTIVITY_LIMIT`. Pure. */
export function appendActivity(log: RrpActivityLog, entry: RrpActivity): RrpActivityLog {
  return { entries: [...log.entries, entry].slice(-ACTIVITY_LIMIT) }
}

/** The most recent entry for a target, if any. */
export function lastActivity(log: RrpActivityLog, target: RrpTarget): RrpActivity | undefined {
  for (let index = log.entries.length - 1; index >= 0; index -= 1) {
    const entry = log.entries[index]
    if (entry?.target === target) return entry
  }
  return undefined
}

/** Whether a writer is still running for a target (tail is a `started` entry). */
export function pendingActivity(log: RrpActivityLog, target: RrpTarget): RrpActivity | undefined {
  const last = lastActivity(log, target)
  return last?.phase === 'started' ? last : undefined
}

/**
 * Best-effort write of one entry. The ledger must never break the writer's
 * own flow, so an append failure is swallowed.
 * @param sink - any append-capable session face.
 * @param entry - the complete entry.
 */
export function recordActivity(sink: { append(type: string, data: unknown): unknown }, entry: RrpActivity): void {
  try {
    sink.append(ACTIVITY_EVENT, entry)
  } catch {
    /* the ledger is best-effort; the authoritative write already happened */
  }
}
