/**
 * dsh-rrp — client (browser) half.
 *
 * Registers the locale dictionaries and the WorldState right-sidebar tab.
 * Everything is a reversible effect tied to this plugin's fiber.
 */
import type { RrpClientContext } from './context-types.ts'
import { registerCopilotTab } from './copilot-tab.tsx'
import { registerGallery } from './gallery-panel.tsx'
import { registerLoreTab } from './lore-tab.tsx'
import { registerWorldStateTab } from './world-state-tab.tsx'

/** Bundle id. The client-modules compose keys on the package name dsh-rrp. */
export const name = 'dsh-rrp/client'

/** Client runtime services required before mounting.
 *  All entries are HOST capabilities the client composition declares; the
 *  panels still treat each one as optional at runtime (see context-types.ts):
 *  `sessions` / `remote` / `layout` absence degrades the gallery, never the
 *  sidebar tabs. `uiConversation` is declared for future composer work and
 *  currently has no consumer. */
// Cordis Remote proxies are namespaced: accessing ctx.remote.agentPresets
// requires declaring 'remote.agentPresets' (not just 'remote').
export const inject = [
  'slots',
  'sidebarRightTabs',
  'locale',
  'sessions',
  'remote',
  'remote.agentPresets',
  'layout',
  'uiConversation',
]

const TAG = '[dsh-rrp]'

/** Locale namespace owned by this plugin; all UI copy goes through it. */
const LOCALE_NS = 'rrp'

const ZH: Record<string, string> = {
  title: '世界状态',
  'guide.description': '查看并就地矫正角色、物品、场景与事件',
  editHint: '就地修改下面的字段并保存；下一轮执笔以最新切面为准（无锁矫正）。',
  save: '保存矫正',
  saving: '保存中…',
  saved: '已保存，下一轮起笔生效',
  saveFailed: '保存失败',
  unsaved: '未保存',
  add: '添加',
  remove: '删除',
  name: '名称',
  'field.affinity': '好感',
  'field.mood': '情绪',
  'field.appearance': '外貌',
  'field.condition': '状态',
  'field.quantity': '数量',
  'field.note': '备注',
  'flag.key': '事件',
  'flag.value': '值',
  'section.scene': '场景',
  'section.characters': '角色',
  'section.inventory': '物品',
  'section.flags': '事件与秘密',
  'scene.location': '地点',
  'scene.time': '时间',
  'scene.weather': '天气',
  'section.coreState': '核心状态',
  'section.dynamicFields': '自定义字段',
  'section.relations': '关系网',
  'relations.none': '暂无关系',
  'budget.title': '上下文体积',
  'budget.card': '卡包设定',
  'budget.summary': '剧情脉络',
  'budget.state': '世界状态',
  'budget.triggers': '条件注入',
  'budget.hint': '注入正文占模型上下文窗口的估算比例',
  'dynamicFields.none': '暂无自定义字段',
  'dynamicFields.remove': '删除字段',
  'dynamicFields.value': '值',
  'dynamicFields.min': '最小值',
  'dynamicFields.max': '最大值',
  'dynamicFields.unbounded': '无限制',
  'dynamicFields.id': '字段 ID',
  'dynamicFields.type': '类型',
  'dynamicFields.initial': '初始值',
  'dynamicFields.cancel': '取消',
  'dynamicFields.idRequired': '字段 ID 不能为空',
  'dynamicFields.idReserved': '字段 ID 不能使用保留名称（characters, inventory, scene, flags）',
  'dynamicFields.idInvalid': '字段 ID 只能包含字母、数字、下划线',
  'dynamicFields.idDuplicate': '字段 ID 已存在',
  'preset.hint': '本会话的 Agent 预设（rp-<卡包>），与「设置 → Agent 预设」里的全局默认不同',
  'chronicler.running': '状态推演进行中，请稍候...',
  'chronicler.completed': '状态推演完成',
  'unsaved.kept': '你的未保存修改已保留，保存后以修改为准',
  noSession: '当前没有会话',
  'world.missing': '尚未建立世界状态，先开一局或手动添加。',
  'activity.title': '最近变更',
  'activity.none': '尚无变更记录',
  'activity.running': '状态推演进行中…',
  'actor.chronicler': '状态推演',
  'actor.summarizer': '剧情脉络',
  'actor.player': '你',
  'phase.committed': '已更新状态',
  'phase.corrected': '已就地矫正',
  'phase.failed': '推演失败',
  'phase.stale': '推演已作废',
  'phase.started': '推演开始',
  'detail.cancelled': '已取消',
  'detail.staleDiscarded': '玩家已就地矫正，推演结果作废',
  'detail.noChange': '（无实质变化）',
  'detail.noTranscript': '没有可用的剧情',
  'detail.nothingToLore': '没有可沉淀的稳定设定',
  'detail.stagedDraft': '草稿：{name}（待确认）',
  'detail.loreWritten': '已沉淀：{name}',
  'detail.playerCorrected': '玩家就地矫正',
  'actor.card': '卡包',
  'actor.scribe': '知识起草',
  'lore.title': '设定集',
  'lore.guide': '把剧情里确立的新设定沉淀为本会话专属的知识；只新增、可审阅、可删除。',
  'lore.topicPlaceholder': '想沉淀什么？（可留空）',
  'lore.draft': '沉淀最近的新设定',
  'lore.drafting': '起草中…',
  'lore.staged': '已生成草稿，等待确认',
  'lore.confirm': '确认写入',
  'lore.discard': '丢弃',
  'lore.discarded': '已丢弃草稿',
  'lore.confirmHint': '确认后本会话下一轮即可按需检索',
  'lore.written': '已沉淀',
  'lore.empty': '本会话还没有沉淀任何设定',
  'lore.removed': '已删除',
  'lore.delete': '删除',
  'lore.failed': '操作失败',
  'lore.noDraft': '目前没有待确认草稿',
  'lore.triggers': '卡包条件设定',
  'lore.triggersEmpty': '本卡包没有条件设定（skill frontmatter 声明 when 后出现在这里）',
  'lore.triggerActive': '生效中',
  'lore.triggerInactive': '未命中',
  'gallery.title': '卡片展厅',
  'gallery.reload': '刷新',
  'gallery.loading': '加载中…',
  'gallery.empty': '没有找到卡包',
  'gallery.pick': '从左侧选择一张卡包，查看它的开场白与设定',
  'gallery.search': '搜索卡包…',
  'gallery.nomatch': '没有匹配的卡包',
  'gallery.player': '玩家角色',
  'gallery.skills': '世界知识',
  'gallery.opening': '开场白',
  'gallery.start': '开始这一局',
  'gallery.starting': '正在建立会话…',
  'gallery.started': '已开始，切回对话',
  'gallery.failed': '操作失败',
  'gallery.selectFailed': '选择预设失败',
  'gallery.orphanSession': '（未能自动清理的残留会话：',
  'gallery.unavailable': '会话服务不可用',
  'gallery.workspace': '工作区',
  'gallery.workspaceUngrouped': '未分组',
  'copilot.title': '副驾驶',
  'copilot.guide': '全知幕僚（OOC 视角）：咨询设定、人物秘密与破局思路，或直接让她代劳修改世界状态、起草设定集。',
  'copilot.placeholder': '问剧情、问设定，或直接下指令…',
  'copilot.send': '发送',
  'copilot.busy': '上一次咨询尚未完成',
  'copilot.failed': '副驾驶出错了，请重试',
  'copilot.empty': '还没有对话。向副驾驶提问，或直接让她修改世界状态。',
  'copilot.you': '玩家',
  'copilot.applied': '已执行变更',
  'copilot.staged': '已起草设定集（待确认）',
  'copilot.undo': '一键撤销',
  'copilot.undoDone': '已撤销上一轮状态变更',
  'copilot.undoEmpty': '没有可撤销的变更',
  'copilot.cleared': '对话已清空',
  'actor.copilot': '副驾驶',
  'detail.copilotUndone': '已撤销副驾驶的状态修改',
  'copilot.copyCode': '复制代码',
  'copilot.copiedCode': '已复制',
}

const EN: Record<string, string> = {
  title: 'World State',
  'guide.description': 'View and correct characters, inventory, scene, and flags',
  editHint: 'Edit fields in place and save. The next turn uses the newest slice (no locks).',
  save: 'Save correction',
  saving: 'Saving…',
  saved: 'Saved — effective next turn',
  saveFailed: 'Save failed',
  unsaved: 'unsaved',
  add: 'Add',
  remove: 'Remove',
  name: 'Name',
  'field.affinity': 'Affinity',
  'field.mood': 'Mood',
  'field.appearance': 'Appearance',
  'field.condition': 'Condition',
  'field.quantity': 'Qty',
  'field.note': 'Note',
  'flag.key': 'Flag',
  'flag.value': 'Value',
  'section.scene': 'Scene',
  'section.characters': 'Characters',
  'section.inventory': 'Inventory',
  'section.flags': 'Events & secrets',
  'scene.location': 'Place',
  'scene.time': 'Time',
  'scene.weather': 'Weather',
  'section.coreState': 'Core State',
  'section.dynamicFields': 'Dynamic Fields',
  'section.relations': 'Relations',
  'relations.none': 'No relations yet',
  'budget.title': 'Context size',
  'budget.card': 'Card setting',
  'budget.summary': 'Chronicle',
  'budget.state': 'World state',
  'budget.triggers': 'Conditional injection',
  'budget.hint': "Estimated share of the model's context window",
  'dynamicFields.none': 'No custom fields yet',
  'dynamicFields.remove': 'Remove field',
  'dynamicFields.value': 'Value',
  'dynamicFields.min': 'Min',
  'dynamicFields.max': 'Max',
  'dynamicFields.unbounded': 'No limit',
  'dynamicFields.id': 'Field ID',
  'dynamicFields.type': 'Type',
  'dynamicFields.initial': 'Initial value',
  'dynamicFields.cancel': 'Cancel',
  'dynamicFields.idRequired': 'Field ID is required',
  'dynamicFields.idReserved': 'Field ID cannot be a reserved name (characters, inventory, scene, flags)',
  'dynamicFields.idInvalid': 'Field ID may only contain letters, digits and underscores',
  'dynamicFields.idDuplicate': 'Field ID already exists',
  'preset.hint': "This session's agent preset (rp-<card>); distinct from the global default in Settings",
  'chronicler.running': 'Chronicler is working, please wait...',
  'chronicler.completed': 'Chronicler updated state',
  'unsaved.kept': 'your unsaved edits were kept and still win after saving',
  noSession: 'No active session',
  'world.missing': 'No world state yet — start a story or add entries manually.',
  'activity.title': 'Recent changes',
  'activity.none': 'No changes recorded yet',
  'activity.running': 'Chronicler is inferring…',
  'actor.chronicler': 'Chronicler',
  'actor.summarizer': 'Summarizer',
  'actor.player': 'You',
  'phase.committed': 'updated state',
  'phase.corrected': 'corrected in place',
  'phase.failed': 'inference failed',
  'phase.stale': 'inference stale',
  'phase.started': 'started',
  'detail.cancelled': 'Cancelled',
  'detail.staleDiscarded': 'Player corrected in place; inference discarded',
  'detail.noChange': '(no material change)',
  'detail.noTranscript': 'No usable story text',
  'detail.nothingToLore': 'Nothing stable to lore',
  'detail.stagedDraft': 'Draft: {name} (awaiting review)',
  'detail.loreWritten': 'Written: {name}',
  'detail.playerCorrected': 'Corrected in place',
  'actor.card': 'Card',
  'actor.scribe': 'Scribe',
  'lore.title': 'Lore',
  'lore.guide': 'Capture newly established lore into this session only; add-only, reviewable, deletable.',
  'lore.topicPlaceholder': 'What to capture? (optional)',
  'lore.draft': 'Capture recent lore',
  'lore.drafting': 'Drafting…',
  'lore.staged': 'Draft staged — waiting for review',
  'lore.confirm': 'Confirm write',
  'lore.discard': 'Discard',
  'lore.discarded': 'Draft discarded',
  'lore.confirmHint': 'Effective in this session from the next turn',
  'lore.written': 'Written',
  'lore.empty': 'No written lore in this session yet',
  'lore.removed': 'Removed',
  'lore.delete': 'Delete',
  'lore.failed': 'Failed',
  'lore.noDraft': 'No draft awaiting review',
  'lore.triggers': 'Card conditional lore',
  'lore.triggersEmpty': 'This card declares no conditional lore (skill frontmatter `when` shows up here)',
  'lore.triggerActive': 'Active',
  'lore.triggerInactive': 'Inactive',
  'gallery.title': 'Card Gallery',
  'gallery.reload': 'Refresh',
  'gallery.loading': 'Loading…',
  'gallery.empty': 'No cards found',
  'gallery.pick': 'Pick a card on the left to preview its opening and setting',
  'gallery.search': 'Search cards…',
  'gallery.nomatch': 'No matching cards',
  'gallery.player': 'Player',
  'gallery.skills': 'World knowledge',
  'gallery.opening': 'Opening',
  'gallery.start': 'Start this story',
  'gallery.starting': 'Creating session…',
  'gallery.started': 'Started — switch back to the chat',
  'gallery.failed': 'Failed',
  'gallery.selectFailed': 'Selecting the preset failed',
  'gallery.orphanSession': ' (orphan session left behind: ',
  'gallery.unavailable': 'Session service unavailable',
  'gallery.workspace': 'Workspace',
  'gallery.workspaceUngrouped': 'Ungrouped',
  'copilot.title': 'Copilot',
  'copilot.guide': 'Omniscient advisor (OOC): ask about lore, secrets and strategy — or let her edit world state and stage lore drafts.',
  'copilot.placeholder': 'Ask about the story, lore, or give a command…',
  'copilot.send': 'Send',
  'copilot.busy': 'The previous turn is still running',
  'copilot.failed': 'Copilot failed; please retry',
  'copilot.empty': 'No conversation yet. Ask the Copilot, or let her edit the world state.',
  'copilot.you': 'Player',
  'copilot.applied': 'Changes applied',
  'copilot.staged': 'Lore staged (awaiting review)',
  'copilot.undo': 'Undo',
  'copilot.undoDone': 'Reverted the last state change',
  'copilot.undoEmpty': 'Nothing to undo',
  'copilot.cleared': 'Conversation cleared',
  'actor.copilot': 'Copilot',
  'detail.copilotUndone': 'Reverted the Copilot edit',
  'copilot.copyCode': 'Copy code',
  'copilot.copiedCode': 'Copied',
}

/** Client plugin body. Registers only reversible effects. */
export function apply(ctx: RrpClientContext): void {
  ctx.effect(() => {
    console.log(`${TAG} client half active`)
    return () => {
      console.log(`${TAG} client half disposed`)
    }
  }, 'dsh-rrp: client lifecycle')

  ctx.effect(() => {
    const offZh = ctx.locale.register(LOCALE_NS, 'zh', ZH)
    const offEn = ctx.locale.register(LOCALE_NS, 'en', EN)
    return () => {
      offZh()
      offEn()
    }
  }, 'dsh-rrp: locale dictionaries')

  registerWorldStateTab(ctx)
  registerLoreTab(ctx)
  registerCopilotTab(ctx)
  registerGallery(ctx)
}
